# Generated by Django 5.0.1 on 2024-02-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exp', models.IntegerField(default=0)),
                ('nop', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
