# Generated by Django 5.0.1 on 2024-02-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('india_job', '0002_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='role',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Sales', 'Sales'), ('Data', 'Data')], default=None, max_length=100),
        ),
    ]
