# Generated by Django 5.0.1 on 2024-02-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('india_job', '0004_alter_resume_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='role',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Sales', 'Sales'), ('Data', 'Data')], default='data', max_length=100),
        ),
    ]
